name: flutter_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_messaging: 16.1.1
  firebase_auth: 6.1.4
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.2.0
  image_picker: ^1.2.1
  sign_in_button: ^4.0.1
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_timezone: ^5.0.1
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Phone_App_Logo.png"
