// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgk8PQCJ7KIEMjuhHz4I0SKFwT4yyZw7s',
    appId: '1:760425569432:web:4cfc037a06a16e045b44ed',
    messagingSenderId: '760425569432',
    projectId: 'memorra-8636f',
    authDomain: 'memorra-8636f.firebaseapp.com',
    storageBucket: 'memorra-8636f.firebasestorage.app',
    measurementId: 'G-H7HWD25EK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeIqxOB96IVuLIrprZL1nX3833NzpSYUQ',
    appId: '1:760425569432:android:39089501f8f019b35b44ed',
    messagingSenderId: '760425569432',
    projectId: 'memorra-8636f',
    storageBucket: 'memorra-8636f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEuVFux3I24Udd5GS49Lm4-8BfaGz9P0M',
    appId: '1:760425569432:ios:3097890bae160e0b5b44ed',
    messagingSenderId: '760425569432',
    projectId: 'memorra-8636f',
    storageBucket: 'memorra-8636f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEuVFux3I24Udd5GS49Lm4-8BfaGz9P0M',
    appId: '1:760425569432:ios:3097890bae160e0b5b44ed',
    messagingSenderId: '760425569432',
    projectId: 'memorra-8636f',
    storageBucket: 'memorra-8636f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgk8PQCJ7KIEMjuhHz4I0SKFwT4yyZw7s',
    appId: '1:760425569432:web:19956284724383425b44ed',
    messagingSenderId: '760425569432',
    projectId: 'memorra-8636f',
    authDomain: 'memorra-8636f.firebaseapp.com',
    storageBucket: 'memorra-8636f.firebasestorage.app',
    measurementId: 'G-CEKX5GEGW3',
  );
}
